### ISSUE TITLE
Can't build in release mode

### ISSUE THREAD

**Issue by gongziya** [ysak-y/flutter_audio_capture#12]
when is run 'flutter build ios', i got this:

```
Building com.example.example for device (ios-release)...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file
version field before submitting to the App Store.
Automatically signing iOS for device deployment using specified development team
in Xcode project: 9CMKDD4ZVM
Running pod install...                                           1,149ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        537ms
Xcode build done.                                            5.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/xxxx/Documents/flutter_audio_pitch/ios/Runner/GeneratedPlugi
    nRegistrant.m:10:9: fatal error: module 'flutter_audio_capture' not found
    @import flutter_audio_capture;
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
    /Users/xxxx/Documents/flutter_audio_pitch/ios/Runner.xcodeproj:
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to
    8.0, but the range of supported deployment target versions is 9.0 to
    14.5.99. (in target 'Runner' from project 'Runner')
```

could anyone please tell me how to fix this error, thx

**Comment by ysak-y** [comment]
Thanks for using my module and congrats for publishing your application!!

Error message shows

> Action Required: You must set a build name and number in the pubspec.yaml file
version field before submitting to the App Store.

So I think you should set build name and number to your pubspec.yaml file.

**Comment by gongziya** [comment]
> Thanks for using my module and congrats for publishing your application!!
> 
> Error message shows
> 
> > Action Required: You must set a build name and number in the pubspec.yaml file
> > version field before submitting to the App Store.
> 
> So I think you should set build name and number to your pubspec.yaml file.

thx for your replay, sorry it's not the real reason that why build failed. after set build name and number in  the pubspec.yaml file, i got the same error:

```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/xxxx/Documents/flutter_audio_pitch/ios/Runner/GeneratedPlugi
    nRegistrant.m:10:9: fatal error: module 'flutter_audio_capture' not found
    @import flutter_audio_capture;
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
    /Users/xxxx/Documents/flutter_audio_pitch/ios/Runner.xcodeproj:
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to
    8.0, but the range of supported deployment target versions is 9.0 to
    14.5.99. (in target 'Runner' from project 'Runner')
```

**Comment by ysak-y** [comment]
> /Users/xxxx/Documents/flutter_audio_pitch/ios/Runner/GeneratedPlugi
    nRegistrant.m:10:9: fatal error: module 'flutter_audio_capture' not found

Oops!! I overlooked. Sorry.
it shows there is no flutter_audio_capture module.

To be clear, do you use other modules? Only flutter_audio_capture doesn't find?

Maybe we need more context to solve this issue.

**Comment by gongziya** [comment]
i use many modules, and only flutter_audio_capture doesn't find.

finally, i set IPHONEOS_DEPLOYMENT_TARGET to 11.4, and fixed it , how amazing😊

here is my runner config:
<img width="524" alt="截屏2021-10-08 下午4 57 42" src="https://user-images.githubusercontent.com/3693462/136528612-db954d7c-0267-40c2-b1e5-ec263b4c3b95.png">

thanks for this project  and your support, it's very usefull to me~
