### ISSUE TITLE
Data format 

### ISSUE THREAD

**Issue by gruvkit** [ysak-y/flutter_audio_capture#2]
Please what is the format/encoding of the data in the buffer. Is it PCM or AAC?

**Comment by ysak-y** [comment]
Currently, PCM only.

https://github.com/ysak-y/flutter_audio_capture/blob/master/ios/Classes/AudioCapture.swift#L30
https://github.com/ysak-y/flutter_audio_capture/blob/master/android/src/main/kotlin/com/ymd/flutter_audio_capture/AudioCaptureStreamHandler.kt#L17

**Comment by gruvkit** [comment]
Okay thank you
