### ISSUE TITLE
Android Kotlin Dependency Issue

### ISSUE THREAD

**Issue by RishabhS2427** [ysak-y/flutter_audio_capture#21]
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_audio_capture' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by Walid-X** [comment]
Maybe u should upgrade your kotlin gradle plugin version to 1.5.20 or higher , in the plugin section ; search for "plugins" in the ide you are using.

**Comment by ysak-y** [comment]
@RishabhS05 Hi, could you please update this library to 1.1.6? I reproduced the error you reported and resolved by the following patch.

https://github.com/ysak-y/flutter_audio_capture/commit/8f4cd5d26c92a79a089751bbdfd8dc030e3a6dff
