### ISSUE TITLE
[BUG?] Doesn't work on Android

### ISSUE THREAD

**Issue by ysak-y** [ysak-y/flutter_audio_capture#25]
Redirect from: https://github.com/ysak-y/flutter_audio_capture/issues/24#issuecomment-1812451986

Could you please more information (e.g. flutter version, Android device version, source code (if you can provide) and so on...) @synchronisator ?

When I run example application in `example` directory with Android emulator (API 33), it seems working. Flutter version is 3.16.0 .

**Comment by synchronisator** [comment]
Hi, i am sorry. I must have made a mistake wile implementing this. I did it again today and it worked like expected under Android.
