### ISSUE TITLE
Several files should be excluded from version control

### ISSUE THREAD

**Issue by dynamicbutter** [ysak-y/flutter_audio_capture#5]
@ysak-y the goal is to remove files from version control to make it easier for other developers to contribute.  That being said I'm still trying to sort out what should be checked in and what should be generated myself.  From what I can tell we should not checkin the following things... 
- .idea/
-  example/ios/Podfile.lock
- example/pubspec.lock
- pubspec.lock

Also updating the .gitignore as described here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/.gitignore.tmpl

**Comment by ysak-y** [comment]
Hi, @jasonletbetter!! Thanks for your report!!
I'll review your issues and pull requests tomorrow 😄

**Comment by dynamicbutter** [comment]
👍

**Comment by ysak-y** [comment]
Resolved by #6.
Thanks for your contribution!!
