### ISSUE TITLE
Flutter audio capture disappears

### ISSUE THREAD

**Issue by applingtalen** [ysak-y/flutter_audio_capture#7]
Hi,
I have installed Flutter_Audio_capture. However, when I click on 'Start' I get the message 'Lost connection to device'. This happens in the Android Emulator (API29). When running on a IOS device in the emulator, I get the message 'cocoapods not installed'. I have tried to get these installed, but couldn't get any further than the message that I do not have writing permission for Library/Ruby/Gems/2.6.0. directory. Don't know what to do next. Flutter doctor announces that I don't have Flutter en Dart plugins installed (which I do), and of course mentions the missing cocoapods.
Willem

**Comment by ysak-y** [comment]
Hi, thank you for your report. :)

Maybe it looks your environment problem. I want to ask you some questions.

1. Did you finish all process of [this install guide?](https://flutter.dev/docs/get-started/install)
2. You can't run only my example app? Can you run another Flutter applications? ([This page will helps you](https://flutter.dev/docs/get-started/codelab))
3. Could you please tell me whole logs when you execute `flutter doctor` or just `flutter`. For example, when I execute `flutter` command, terminal shows me as below (It's just help message).

```
$ flutter
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with --help, shows hidden options.
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.

Available commands:
  analyze           Analyze the project's Dart code.
  assemble          Assemble and build Flutter resources.
  attach            Attach to a running app.
  bash-completion   Output command line shell completion setup scripts.
  build             Build an executable app or install bundle.
  channel           List or switch Flutter channels.
  clean             Delete the build/ and .dart_tool/ directories.
  config            Configure Flutter settings.
  create            Create a new Flutter project.
  devices           List all connected devices.
  doctor            Show information about the installed tooling.
  downgrade         Downgrade Flutter to the last active version for the current channel.
  drive             Run integration tests for the project on an attached device or emulator.
  emulators         List, launch and create emulators.
  format            Format one or more Dart files.
  gen-l10n          Generate localizations for the current project.
  install           Install a Flutter app on an attached device.
  logs              Show log output for running Flutter apps.
  precache          Populate the Flutter tool's cache of binary artifacts.
  pub               Commands for managing Flutter packages.
  run               Run your Flutter app on an attached device.
  screenshot        Take a screenshot from a connected device.
  symbolize         Symbolize a stack trace from an AOT-compiled Flutter app.
  test              Run Flutter unit tests for the current project.
  upgrade           Upgrade your copy of Flutter.
```

**Comment by applingtalen** [comment]
Hi,
I carefully followed every step of the installation of Flutter.
I can run other Flutter applications.
When I execute the Flutter command I get the same result as shown. 
However, in my project structure I get the following message Problem : 1:Module flutter_recorder_android: invalid item 'Flutter for Android' in the dependencies list. I don't know what this means.
Willem

**Comment by ysak-y** [comment]
Ah... okay, maybe I realize the reason why can't run.
I'll fix it ASAP. And could you try run it by your real Android/iOS device?

**Comment by ysak-y** [comment]
Hi, I've investigated about this issue. In my environment, example app works when run on Intel MacBook Pro, crashes when run on Apple Silicon Mac Mini (which doesn't have any built-in microphone).

Could you please tell me about your PC?

**Comment by applingtalen** [comment]
Hi,
My computer is an Apple MacBook Air, OS Catalina.
Willem
